name: pioneer_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2 #icon库
  dio: 3.0.9 #网络库
  toast: ^0.1.5 #toast提示
  flutter_swiper: ^1.1.6 #banner
  screen_ratio_adapter: ^0.0.2 #屏幕适配
  webview_flutter: ^0.3.22+1 #原生webView插件
  shared_preferences: ^0.5.7+3 #本地存储
  provider: ^4.0.5 #操作provider通知使用主题切换
  flustars: ^0.2.6+1
  path_provider: ^1.6.9 #获取本地缓存目录 使用清除缓存功能
  share: ^0.6.1+1 #分享
  #数据库依赖
  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/ic_logo.png
    - images/ic_picture_temp.png
    - images/ic_picture_temp_night.png

  fonts:
    - family: ThemeIcons
      fonts:
        - asset: lib/assets/fonts/iconfont.ttf